name = "zephyr-colorglyph-ingestion"

[[tables]]
name = "glyphs"

[[tables.columns]]
name = "hash"
col_type = "BYTEA"

[[tables.columns]]
name = "owner"
col_type = "BYTEA"

[[tables.columns]]
name = "minter"
col_type = "BYTEA"

[[tables.columns]]
name = "width"
col_type = "BYTEA"

[[tables.columns]]
name = "length"
col_type = "BYTEA"

[[tables.columns]]
name = "colors"
col_type = "BYTEA"